defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: payments_development
  host: localhost
  <<: *defaults

test:
  database: payments_test
  host: localhost
  min_messages: WARNING
  <<: *defaults
